### ISSUE TITLE
Resourceful Bees Centrifuge Recipes not working

### ISSUE THREAD

**Issue by Nyndaris** [AllTheMods/ATM-6#1384]
**Describe the bug**
Version 1.5.10
Mod Resourceful Bees
Multiblock Centrifuge is not working anymore.
JEI shows no recipes for the Honeycombs/Blocks.

**To Reproduce**

Just try to process honeycombs or honeycomb blocks.

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by skiwi184** [comment]
Neither the Muliblock, the hand cranked or the "simple" one works the only honey combs that work are the standart Minecraft combs

**Comment by Brytha** [comment]
I only have this issue on a multiplayer server.

**Comment by Paper-28** [comment]
Same problem - multiblock resourceful bees centrifuge process only vanilla honeycombs - not the others

**Comment by Brytha** [comment]
Honeycombs are still not being processed on multiplayer after patch 1.5.10b

**Comment by Paper-28** [comment]
Issue still persist -update to 10b did not solve it

**Comment by Flipje666** [comment]
Can confirm I'm experiencing the same issue, world that's been updated on a LAN server starting on 1.5.8 and now on 1.5.10b. 
New SP worlds on 1.5.10b have all the recipes etc working fine, but this LAN server has the same issue: 
- (any) Centrifuge only processes vanilla honeycombs, all other honeycombs do nothing.
- Centrifuge doesn't show in JEI as a processor for all honeycombs except vanilla.

**Comment by Pdiddy973** [comment]
this seems to be a multiplayer only issue, working with the Resourceful Bees to try an resolve

**Comment by darkcamo12** [comment]
so I've been testing for the last 2 days to work out which mod was causing this to happen on the servers 

so dropping back both phosphophyllite and biggerreactors a version that was either on 1.5.8b or 1.5.9b seems to have fixed the issue of the recipes not showing and centrifuges not processing 

i tried running version 1.5.9b (which the centrifuges were working in) and tested the centrifuges (they were working of cause) and then put the version of both phosphophyllite and biggerreactors that was in version 1.5.10b in and said centrifuge stopped processing along with the recipes no longer showing

**Comment by Paper-28** [comment]
Yes, can confirm - 1.5.9b is last that works

**Comment by Kipex** [comment]
Might not help finding the cause, but just wanted to chime in to say this isn't a problem we suffer from in our server. My multiblock centrifuge is working fine. World started in 1.5.1, updated to 1.5.3b, to 1.5.5, and finally to 1.5.10 which we are currently running. 

The only mods we have disabled from the pack are FTB Ultimine (don't like), NetherPortalFix (causes suffocation loop), and Shrink (crouch-height-bug). Hope you figure it out!

**Comment by Kipex** [comment]
Interestingly enough, after our server "crashed" due to a forgotten windows update, this problem is now also affecting us.

**Comment by whatthedrunk** [comment]
This has been fixed in dev. 1.6.0 should be out before the weekend fixing a lot of issues due to some cross mod issues that were only found on some OS's.

**Comment by RogueLogix** [comment]
fixed in this commit https://github.com/BiggerSeries/Phosphophyllite/commit/846fdcf77e171983b41675fe48c66945a5593a6e#diff-8db46574c2c5465015251faa1f851ffd277a3992b73d87a6c697866233287f74
related to https://github.com/AllTheMods/ATM-6/issues/1399
new BiR/Phos version on curseforge

**Comment by whatthedrunk** [comment]
Fixed in 1.6.0 that just relased.

**Comment by HaansJob** [comment]
Problem is back with Wither/ed, Lava and Blazing Combs

**Comment by Pdiddy973** [comment]
update to 1.6.3c

**Comment by Abadeerski** [comment]
Hello, I'm not sure if a solution has been found for this issue or not but I started an ATM 6 server a few days ago and I am having the same issue. I am the only one with this issue on the server and we are on version 1.7.11 any help would do wonders as this was the mod I was most excited to do :\

**Comment by andre-barata** [comment]
I'm playing ATM 6 v1.8.10 in single player, and the bug still exists, the centrifuges only work with vanilla honeycombs

**Comment by wafebreaker** [comment]
1.8.20 the problem still exists. Only vanilla Honeycombs. Is it so hard do fix this problem? I mean the mod is actually unplayable.
