### ISSUE TITLE
ATM 6 1.5.0 Resourceful Bees get lost and don't go back to hive/apiary.

### ISSUE THREAD

**Issue by SophisticaSean** [AllTheMods/ATM-6#966]
**Describe the bug**
Resourceful bees stopped working. I upgraded 1.3.9b ResourcefulBees to the most recent version that ATM 6 1.5.0 uses before 1.5.0 came out. I upgraded my world to 1.5.0 and RBees stopped working entirely. I have several Tier 4 Apiaries that I've broken and placed over and over again. I've built new apiaries and swapped bees out and they all have the same problem. Max 2 bees will actually continue working. All other bees seem to get lost and never go back into the apiary. I cannot figure out a work around.

**To Reproduce**
Place Tier4 Apiary multiblock.
Put 6 different bees in the multiblock and populate their flowers.
Unlock them and wait.
Observe most of them flying around aimlessly refusing to go back into the apiary.
Observe little to no honeycomb production.

This is the exact same behavior that ResourcefulBees had in RSB version ResourcefulBees1.16.3-1.16.4-0.5.7b on ATM 1.3.9b. I manually upgraded to ResourcefulBees1.16.3-1.16.4-0.5.8b and it fixed the issue but it seems to have returned.

**Comment by SophisticaSean** [comment]
I wonder if it's RSBees being broken on 1.16.5. I just tested it again with a fresh world and ATM 6 1.5.0 and RSbees don't work at all. They leave the apiary 1-2 times and never come back and just wonder indefinitely and make no combs/blocks.

**Comment by YveanaMisp** [comment]
Im having the same problem with my diamond bees

**Comment by YveanaMisp** [comment]
i may also be having it with the oreo and wither and allthemodium that or they are just REALLYLLYLYLYLYLLYLYYY SLOW!!!!

**Comment by delta2k** [comment]
i didn't update to 1.16.5. i stayed on ATM 6-1.4.1 but i decided to only install Performant mod. the bees did not want to go back into the apiary. so removed the mod and works fine again. if somebody could run tests on ATM 6 1.5.0 above pretty sure should this could be causing the mod conflict problem.

**Comment by joolicious** [comment]
Still an issue in 1.5.1 - I'm using Tier1 apiary and my netherite, allthemodium and ghost bees will not go back to the apiary, while others do.

**Comment by YveanaMisp** [comment]
a new version just came out its resourcefulbees-1.16.5-0.5.9_3b
it doesnt say any fixes about what we are talking about but  it does say - Hopefully fixed bees suffocating inside of the apiary and hives when they leave.
- added new "angry" trait
- fixed a missing angry texture resulting in the bee having a missing texture
- fixed entity error spam when an invalid bee is attempting to leave an apiary
- added new missing texture

**Comment by Pdiddy973** [comment]
I have noticed prefomant can effect the bees AI, we added it in 1.5.0, I have seen the bees work more normally after removing it so I'm going to look into the cfgs to see what we can do about it.

Also try to break/replace the hive/apiaries after you update/ if you remove prefomant that should fix the pathing.

I would also stick with the pack version of RB, since the new ones have had some issues but I have been working with them to try and do some bug fixing.

**Comment by RickyGeo** [comment]
ahh so that the issue :) why me bee stop working and just wondering :)

**Comment by SophisticaSean** [comment]
Yeah I've tried to break and replace the blocks and it doesn't fix their AI. I loaded up a brand new single player world and confirmed the issue as well.

**Comment by Pdiddy973** [comment]
> Yeah I've tried to break and replace the blocks and it doesn't fix their AI. I loaded up a brand new single player world and confirmed the issue as well.

Did you remove the mod performant? That has been known to mess with the bees AI

**Comment by WinterIsPretty** [comment]
it still happens
